export default [
    ["Nerd For Life", "No Fun League", "National Football League", "National Food Laboratory"],
    ["32", "24", "48", "12"],
    ["Chicago Bears", "Green Bay Packers", "New York Giants", "Miami Dolphins"],
    ["New York Yankees", "New York Rangers", "New York Jets", "New York Knicks"],
    ["4", "2", "6", "7"],
    ["Oakland Raiders", "New England Patriots", "San Francisco 49ers", "New York Giants"],
    ["1924", "1927", "1920", "1933"],
    ["6", "2", "4", "8"],
    ["44", "62", "53", "59"],
    ["16", "18", "12", "14"],
    ["12 Minutes", "10 Minutes", "15 Minutes", "16 Minutes"],
    ["1960", "1974", "1980", "1968"],
    ["14", "16", "18", "17"],
    ["14", "8", "6", "12"],
    ["1970", "1972", "1971", "1969"],
    ["1920", "1967", "1935", "1944"],
    ["Don Shula", "Tom Landry", "Bill Belichick", "George Halas"],
    ["Pittsburgh Steelers", "Arizona Cardinals", "Dallas Cowboys", "Green Bay Packers"],
    ["Dallas Cowboys", "New England Patriots", "Cleveland Browns", "Green Bay Packers"],
    ["New England Patriots", "Dallas Cowboys", "Pittsburgh Steelers", "Green Bay Packers"],
    ["Bill Belichick", "Tom Landry", "Vince Lombardi", "Tom Coughlin"],
    ["Dallas Cowboys", "New England Patriots", "Green Bay Packers", "Pittsburgh Steelers"]
];