export default [
    "What does the NFL stand for?",
    "How many teams play in the NFL?",
    "Which one of the following teams were not apart of the original NFL?",
    "Which of these teams competes in the NFL?",
    "How many points is a touchdown worth?",
    "Who won the Super Bowl in 2019?",
    "What year was the NFL founded?",
    "How many divisions does the NFL have?",
    "How many players are on each teams roster?",
    "How many games are played in the regular season?",
    "How long is each quarter in a game?",
    "When was overtime added to NFL games?",
    "How many weeks are in a regular NFL season?",
    "How many teams make it to the playoffs?",
    "In what year did the American Football League merge with the NFL?",
    "When was the first Super Bowl held?",
    "Who is the winningest head coach in the NFL?",
    "Which team was not in the NFL in 1920?",
    "Which team has the most regular season wins in the NFL?",
    "Which team has won the most NFL championships?",
    "Which coach has won the most Super Bowls?",
    "Which team has the most Super Bowl appearances?"
]; 