export default [
    "National Football League",
    "32",
    "Miami Dolphins",
    "New York Jets",
    "6",
    "New England Patriots",
    "1920",
    "8",
    "53",
    "16",
    "15 Minutes",
    "1974",
    "17",
    "12",
    "1970",
    "1967",
    "Don Shula",
    "Pittsburgh Steelers",
    "Chicago Bears",
    "Green Bay Packers",
    "Bill Belichick",
    "New England Patriots"
];